### ISSUE TITLE
Errors occur when trying to run `prototype_omip_simulation.jl`

### ISSUE THREAD

**Issue by francispoulin** [CliMA/ClimaOcean.jl#108]
Following the disucssion [here](https://github.com/CliMA/ClimaOcean.jl/issues/106#top) with @simone-silvestri and @glwagner , I tried running `prototype_omip_simulation.lj`. 

It didn't get very far as it could not load `OceanSimuliations`.  See below.

```
julia> using ClimaOcean.OceanSimulations
ERROR: UndefVarError: `OceanSimulations` not defined
```

**Comment by simone-silvestri** [comment]
you probably have to instantiate the `prototype_omip_simulation` folder with `add ../` to get the current version of `ClimaOcean`.

**Comment by simone-silvestri** [comment]
Note that the `prototype_omip_simulation` folder has it's own Manifest.toml and Project.toml, so you have to activate the environment of that folder

**Comment by glwagner** [comment]
I guess we should put a README in `prototype_omip_simulation` that explains how to use it.

**Comment by francispoulin** [comment]
Thanks!

I ran `julia --project` and then did `instantaite` and I'm happy to say this fixed the problem.

I'm now running the example and it's making progress.  

I presume someone else will modify the README to include another piece of information?

**Comment by glwagner** [comment]
@francispoulin you can help if you like!

**Comment by francispoulin** [comment]
Thanks @glwagner.  I will try and put together a PR tomorrow that includes more heplful information.

Following up on #109 , I specify the ECCO password and login.

Now the problem I have is that it does not understand `TRG`.  See below.

Trying to run `tripolar_specific_methods.jl` gives the same error.

```
julia> include("prototype_omip_simulation.jl")
[ Info: Precompiling OrthogonalSphericalShellGrids [c2be9673-fb75-4747-82dc-aa2bb9f4aed0]
ERROR: LoadError: UndefVarError: `TRG` not defined
Stacktrace:
 [1] include(fname::String)
   @ Base.MainInclude ./client.jl:489
 [2] top-level scope
   @ ~/Software/ClimaOcean.jl/prototype_omip_simulation/prototype_omip_simulation.jl:28
 [3] include(fname::String)
   @ Base.MainInclude ./client.jl:489
 [4] top-level scope
   @ REPL[4]:1
in expression starting at /home/fpoulin/Software/ClimaOcean.jl/prototype_omip_simulation/tripolar_specific_methods.jl:23
in expression starting at /home/fpoulin/Software/ClimaOcean.jl/prototype_omip_simulation/prototype_omip_simulation.jl:28
```

**Comment by glwagner** [comment]
Ok but that line is just 

https://github.com/CliMA/ClimaOcean.jl/blob/514135fc9a1016ec0c32081fe3914e789b3d35ca/prototype_omip_simulation/tripolar_specific_methods.jl#L23

Doesn't that mean that you don't have the right version of `OrthogonalSphericalShellGrids`?

**Comment by simone-silvestri** [comment]
hmmm right, you might want to try with:
```julia
(prototype_omip_simulation) pkg> add OrthogonalSphericalShellGrids@v0.1.1
```
I do not get any error if I do
```
julia> using OrthogonalSphericalShellGrids: TRG
```

**Comment by simone-silvestri** [comment]
Anyways, it looks like there is some cleanup to do in this folder...
As soon as https://github.com/CliMA/ClimaOcean.jl/pull/104 passes and is merged I ll make sure there is some README here and the prototype_omip_simulation.jl file runs smoothly.

**Comment by francispoulin** [comment]
Thanks again!

Yes, that did the trick and I can now add `TRG`.

When I try running the script I get an error that scalar indexing is disallowed.   I am running julia 1.10.0.  Should I be using another version?  Or maybe another library needs to be updated?

I'll change the name of the issue and open it up again.

```
julia> include("prototype_omip_simulation.jl")
[ Info: Regridding bathymetry from existing file ./ETOPO_2022_v1_60s_N90W180_surface.nc.
ERROR: LoadError: Scalar indexing is disallowed.
Invocation of getindex resulted in scalar indexing of a GPU array.
This is typically caused by calling an iterating implementation of a method.
Such implementations *do not* execute on the GPU, but very slowly on the CPU,
and therefore should be avoided.
```

**Comment by simone-silvestri** [comment]
Right, this is the correct branch to use https://github.com/CliMA/OrthogonalSphericalShellGrids.jl/pull/10
I will try fixing this problem with a gpu-based `OffsetArray`.

**Comment by francispoulin** [comment]
Thanks @simone-silvestri !  I'm happy to try again after you have merged the correct branch.

**Comment by simone-silvestri** [comment]
We also have to wait this https://github.com/JuliaRegistries/General/pull/112296 because I changed the URL of the repository.

**Comment by glwagner** [comment]
@simone-silvestri you can add a compat entry to `Project.toml` to enforce the version

**Comment by glwagner** [comment]
@francispoulin ok but did you try

```julia
pkg> add https://github.com/CliMA/OrthogonalSphericalShellGrids.jl#ss/new_bump
```

?

It was mentioned in separate posts, but @simone-silvestri said that you need to use the branch on PR #10. Clicking on the link we see the branch is called `ss/new_bump`. Therefore when adding the package using the url command, you have to specify that you want `ss/new_bump` branch.

**Comment by francispoulin** [comment]
I'm happy to say that it worked!

I tried it on my laptop and it died because it only had 15 GB of GPU memory and it needs more.  I presume a lot more.

I'll try this on a cluster soon and I hope that 40 GB is enough memory.
