### ISSUE TITLE
OceanArtifacts.jl points to a branch

### ISSUE THREAD

**Issue by navidcy** [CliMA/ClimaOcean.jl#11]
should we change this to the `main` branch?

https://github.com/CliMA/ClimaOcean.jl/blob/ac875e433bf267c712081ea0ea6eefe700a83e8f/src/ClimaOcean.jl#L9

**Comment by glwagner** [comment]
We can but something we need to discuss is whether we need a dedicated repo (or in fact, another method) for serving data for ClimaOcean. For example the new quarter degree data did not fit in OceanangiansArtifacts and I had to create a new repo in PR #6 

https://github.com/CliMA/ClimaOcean.jl/blob/235f53a59fd09acd9f6ff862f67b24e83d02f451/src/ClimaOcean.jl#L14
