### ISSUE TITLE
Why is `timeout_in_minutes` written twice?

### ISSUE THREAD

**Issue by glwagner** [CliMA/ClimaOcean.jl#144]
It appears twice in `examples_build.yml`:

https://github.com/CliMA/ClimaOcean.jl/blob/ad28ba8acca2ecff7ab94f25ffb0a72e0ae3429a/.buildkite/examples_build.yml#L7

https://github.com/CliMA/ClimaOcean.jl/blob/ad28ba8acca2ecff7ab94f25ffb0a72e0ae3429a/.buildkite/examples_build.yml#L54

@simone-silvestri

**Comment by simone-silvestri** [comment]
I think only the second one is required
