### ISSUE TITLE
Why does example use `maximum(abs, interior(u))`?

### ISSUE THREAD

**Issue by glwagner** [CliMA/ClimaOcean.jl#158]
We should be using `maximum(abs, u)`, shouldn't we?

https://github.com/CliMA/ClimaOcean.jl/blob/dcdc862c73528ea93d68996e97dbb96cdaa05b5f/examples/near_global_ocean_simulation.jl#L155

**Comment by glwagner** [comment]
cc @simone-silvestri

**Comment by simone-silvestri** [comment]
Switch to `maximum(abs, u)` is a good idea!
