### ISSUE TITLE
Why not use the actual freezing temperature for `MinimumTemperatureSeaIce`?

### ISSUE THREAD

**Issue by glwagner** [CliMA/ClimaOcean.jl#173]
The main benefit is simply that it makes sense rather than being random (and assuming S = 35) or something.

`ClimaSeaIce` has a simple tool to diagnose the melting temperature so its not hard at all.

https://github.com/CliMA/ClimaOcean.jl/blob/b3b44b709c70b296adb63cf7b2f4552334dcfd1b/src/OceanSeaIceModels/minimum_temperature_sea_ice.jl#L20

cc @simone-silvestri wondering if there is a reason for this or just convenience?

**Comment by glwagner** [comment]
side node is the function has the wrong argument order for a mutating function that uses dispatch (should be `mutated_args..., dispatch_args... other_args...`).

https://github.com/CliMA/ClimaOcean.jl/blob/b3b44b709c70b296adb63cf7b2f4552334dcfd1b/src/OceanSeaIceModels/minimum_temperature_sea_ice.jl#L22-L26

**Comment by glwagner** [comment]
Shouldn't we also prevent the ocean from going below the freezing temperature btw? Not just limit fluxes?

**Comment by simone-silvestri** [comment]
Nono, it is just convenience. I am not sure how "physical" this method is, but we can use a freezing temperature. If we use a correct freezing temperature indeed, we need to limit the interior. Using a constant temperature we should not need it as if the model is conservative (which is not because of the linear free surface) it should not be able to go below that minimum temperature in the interior if we limit the fluxes.

**Comment by glwagner** [comment]
The point is not to make it more physical but just make it easier to understand. -1.8 is random whereas the freezing temperaure, is, well, the freezing temperature... it's more logical...

**Comment by glwagner** [comment]
The model can go below freezing transiently, how would it warm back up?

**Comment by simone-silvestri** [comment]
Right here, the warming is allowed. It is probably not extremely physical because the warming should be subject to a different albedo if we want to go the "physical" route.

**Comment by simone-silvestri** [comment]
Ok, let's add the freezing temperature from ClimaSeaIce.

**Comment by glwagner** [comment]
Ok!

It occurs to me that one may not want to auto-adjust internal ocean temperatures to freezing because the model will no longer conserve energy. Just turning off fluxes maintains conservation. So if we want to adjust ocean temperatures to freezing, it should probably be an option rather than the only possibility (and maybe we don't need it at all).

As an example. I ran a simulation that accidentally removed continents, and the ocean temperature plunged to -40...

**Comment by simone-silvestri** [comment]
Yeah, longwave radiation is quite powerful! 😄

**Comment by glwagner** [comment]
Also the atmospheric temperature over siberia is pretty cold.

**Comment by simone-silvestri** [comment]
should be closed
