### ISSUE TITLE
JRA55_field_time_series not found

### ISSUE THREAD

**Issue by waywardpidgeon** [CliMA/ClimaOcean.jl#192]
For some reason the function/method JRA55_field_time_series cannot be found . This applies to the ClimaOcean examples 
generate_atmos_dataset.jl and inspect_JRA55_data.jl with environment status:

Status `C:\Users\kab\.julia\environments\v1.10\Project.toml`
  [0376089a] ClimaOcean v0.1.3
  [e9467ef8] GLMakie v0.10.13
⌅ [033835bb] JLD2 v0.4.53
⌅ [9e8cae18] Oceananigans v0.90.14
  [de0858da] Printf
Info Packages marked with ⌅ have new versions available but compatibility constraints restrict them from upgrading. To see why use `status --outdated

This is on a Win 11 machine with Julia v1.10.5

The two examples were working in mid September. 
Thanks - Kevin

**Comment by waywardpidgeon** [comment]
I should have added. the definition of  JRA55_field_time_series is in src/DataWrangling/JRA55.jl at line 318 in the module JRA55. 
I don't think this has changed.

**Comment by glwagner** [comment]
Can you provide the code you are running that does not work?

**Comment by waywardpidgeon** [comment]
The code is from for example generate_atmos_dataset.jl:

using ClimaOcean
using Oceananigans
using JLD2

time_indices = Colon() # a fix from time_indices = 1:1

qt = ClimaOcean.JRA55.JRA55_field_time_series(:specific_humidity; time_indices)

Strange to say, on my home win 10 machine it works as it did before.  Maybe it never worked on the win 11 PC!

Thanks - Kevin


Emeritus Professor Kevin Broughan
Department of Mathematics and Statistics
School of Computing and Mathematical Sciences
University of Waikato, Hamilton 3240
New Zealand
Tel: +(64)(0)211210446
Web: https://kevinbroughan.nz
________________________________

**Comment by waywardpidgeon** [comment]
More info. I attempted under win 11 with a su windows power shell with no change. I re added the ClimaOcean package also with no change. I looked at the packages in ~/.julia/packages and found ClimaOcean\JXyuK\src\DataWrangling\JRA55.jl but the funny folder seems normal.

**Comment by waywardpidgeon** [comment]
More under win 11: in my .julia package folder in the DataWrangling subfolder (DW for short) there are files DW.jl, ECCO2.jl, JRA55.jl (and the same on my set of previous versions of ClimaOcean) but on github in the ClimaOcean repo we see in DW a subfolder ECCO and the files DW.jl and JRA55.jl (and inpaint_marsk.jl). I doubt whether this is related to the problem, but I will check at home for the win 10 file structure. 
Ignore the two previous comments if they don't related to this issue.

**Comment by glwagner** [comment]
Check what branch you are on and make sure you are up to date with the remote repo

**Comment by waywardpidgeon** [comment]
I think both machines have ClimaOcean v0.1.3 - Is that what you mean by "up-to-date repo" ?
The win 10 machine was at Julia v 1.10.5. I updated to 1.11 and the error returned. I then using juliaup returned to 1.10.5 and the error remained. 

Here is the win 10 machines status:
Status `C:\Users\Kevin.DESKTOP-SVS3IFD\.julia\environments\v1.10\Project.toml`
  [79e6a3ab] Adapt v4.0.4
  [179af706] CFTime v0.1.3
  [052768ef] CUDA v5.5.2
⌃ [13f3f980] CairoMakie v0.12.13
  [0376089a] ClimaOcean v0.1.3
  [8bb1440f] DelimitedFiles v1.9.1
⌃ [e9467ef8] GLMakie v0.10.13
  [5c1252a2] GeometryBasics v0.4.11
⌅ [033835bb] JLD2 v0.4.53
  [63c18a36] KernelAbstractions v0.9.28
⌃ [85f8d34a] NCDatasets v0.12.17
  [30363a11] NetCDF v0.12.0
⌅ [9e8cae18] Oceananigans v0.90.14
  [6c6a2e73] Scratch v1.2.1
  [ade2ca70] Dates
  [de0858da] Printf

Thanks - Kevin

**Comment by glwagner** [comment]
> I think both machines have ClimaOcean v0.1.3 - Is that what you mean by "up-to-date repo" ?

Yes in part, I mean if you are looking at the source code on your machine, then you want to make sure you are on the `main` branch and that your local repository is up to date with the "remote" (ie the one here on github). That ensures that you're running the latest code (where some of the problems you're encountering may already be fixed) and also that we are using the same code.

The latest version is 0.2.1:

https://github.com/CliMA/ClimaOcean.jl/blob/fc175f6c6b3e095bd460d10d323e4361006a5008/Project.toml#L5

but it could also be a good idea to work from the `main` branch for the purposes of error reporting since that's where we'll fix problems.

> The win 10 machine was at Julia v 1.10.5. I updated to 1.11 and the error returned. I then using juliaup returned to 1.10.5 and the error remained.

We've found some issues with julia 1.11 so lets stick to 1.10.5 for now

**Comment by glwagner** [comment]
Here's what I find on `main`:

```julia
shell> git status
On branch main
Your branch is up to date with 'origin/main'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	Manifest.toml

nothing added to commit but untracked files present (use "git add" to track)

(ClimaOcean) pkg> st
Project ClimaOcean v0.2.1
Status `~/Projects/ClimaOcean.jl/Project.toml`
  [79e6a3ab] Adapt v4.0.4
  [179af706] CFTime v0.1.3
  [052768ef] CUDA v5.5.2
  [6ba0ff68] ClimaSeaIce v0.1.2
  [9c784101] CubicSplines v0.2.1
  [124859b0] DataDeps v0.7.13
  [787d08f9] ImageMorphology v0.4.5
⌅ [033835bb] JLD2 v0.4.53
  [63c18a36] KernelAbstractions v0.9.28
  [85f8d34a] NCDatasets v0.14.5
⌅ [9e8cae18] Oceananigans v0.91.15
  [c2be9673] OrthogonalSphericalShellGrids v0.1.5
  [6c6a2e73] Scratch v1.2.1
  [d496a93d] SeawaterPolynomials v0.3.5
  [90137ffa] StaticArrays v1.9.7
⌅ [49b00bb7] SurfaceFluxes v0.11.0
  [b60c26fb] Thermodynamics v0.12.8
  [ade2ca70] Dates
  [f43a241f] Downloads v1.6.0
  [de0858da] Printf
  [10745b16] Statistics v1.10.0
Info Packages marked with ⌅ have new versions available but compatibility constraints restrict them from upgrading. To see why use `status --outdated`

julia> using ClimaOcean

julia> qt = ClimaOcean.JRA55.JRA55_field_time_series(:specific_humidity)
640×320×1×2 FieldTimeSeries{Oceananigans.OutputReaders.InMemory} located at (Center, Center, ⋅) on Oceananigans.Architectures.CPU
├── grid: 640×320×1 LatitudeLongitudeGrid{Float32, Oceananigans.Grids.Periodic, Oceananigans.Grids.Bounded, Oceananigans.Grids.Flat} on Oceananigans.Architectures.CPU with 3×3×0 halo and with precomputed metrics
├── indices: (:, :, :)
├── time_indexing: Cyclical(period=21600.0)
├── backend: InMemory()
└── data: 646×326×1×2 OffsetArray(::Array{Float32, 4}, -2:643, -2:323, 1:1, 1:2) with eltype Float32 with indices -2:643×-2:323×1:1×1:2
    └── max=0.0246766, min=0.0, mean=0.0069465
```

**Comment by glwagner** [comment]
Hmm ok when I install from a clean environment I get version 0.1.3. I think that 0.2 is not registered --- so I registered it here: https://github.com/CliMA/ClimaOcean.jl/commit/768ec7679c8b9e2caa556e5e07838b86c1b2e97f

In the meantime, from a clean environment you can try:

```julia
(Clean) pkg> add ClimaOcean#main
```

from package manager mode.

Or:

```julia
julia> using Pkg; Pkg.add(url="https://github.com/CliMA/ClimaOcean.jl.git", rev="main")
```

Then I think this should work:

```julia
julia> using ClimaOcean

julia> qt = ClimaOcean.JRA55.JRA55_field_time_series(:specific_humidity)
640×320×1×2 FieldTimeSeries{Oceananigans.OutputReaders.InMemory} located at (Center, Center, ⋅) on Oceananigans.Architectures.CPU
├── grid: 640×320×1 LatitudeLongitudeGrid{Float32, Oceananigans.Grids.Periodic, Oceananigans.Grids.Bounded, Oceananigans.Grids.Flat} on Oceananigans.Architectures.CPU with 3×3×0 halo and with precomputed metrics
├── indices: (:, :, :)
├── time_indexing: Cyclical(period=21600.0)
├── backend: InMemory()
└── data: 646×326×1×2 OffsetArray(::Array{Float32, 4}, -2:643, -2:323, 1:1, 1:2) with eltype Float32 with indices -2:643×-2:323×1:1×1:2
    └── max=0.0246766, min=0.0, mean=0.0069465
```

Let me know if that's what you get @waywardpidgeon

**Comment by waywardpidgeon** [comment]
Yes,  I do get that at win 10 (I mean installing ClimaOcean@0.2.1 in the way you described, i.e. ClimaOcean#main in an otherwise empty environment. I'll not be back at work until next week and will check win 11 then. I'll (probably) close the issue then.
Thanks heaps.

**Comment by glwagner** [comment]
Thanks for bearing with us while we build this infrastructure out. Your help is appreciated.

**Comment by waywardpidgeon** [comment]
No problem, and none with win 11 including JRA55 data. The GPU was active during the movie production with no changes to the code -  I did add/using CUDA which might not have been needed. It was very fast.
