### ISSUE TITLE
Why does `ECCO_field_time_series` put `metadata` in `path`?

### ISSUE THREAD

**Issue by glwagner** [CliMA/ClimaOcean.jl#202]
Is this a bug?

https://github.com/CliMA/ClimaOcean.jl/blob/1280a9dab180e11e6c19f8f019abab0825f1670f/src/DataWrangling/ECCO/ECCO_restoring.jl#L130

The `metadata` isn't a path. Though it does contain information about the path. But I think it can produce confusion or lead to a fragile system if we put non-paths in `path`.

I'd like to fix this but I need to understand what is trying to be achieved to come up with an alternative design. The `FieldTimeSeries` already has an extensible design that uses the `backend`, so that's probably where `metadata` information should go if things other than just the `path` are needed.

**Comment by simone-silvestri** [comment]
Should be closed by #198
