### ISSUE TITLE
Avoiding redundant data download in parallel plus a nice way to download data prior to launching an MPI job

### ISSUE THREAD

**Issue by glwagner** [CliMA/ClimaOcean.jl#206]
If we try to run a simulation for the first time with `mpiexec`, I think we can end up redundantly downloading the same data from different MPI processes.

I'm not sure the best way to handle this --- we could only download from rank 0, or we can somehow distribute the downloading amongst processes (even cooler). 

A related issue is that we don't have a simple way to download data in isolation before running a script (the data is all downloaded automatically by trying to run a simulation, which is very nice of course). But probably there are situations where a user may want to get the downloading out of the way in advance before launching a job and it would be nice to make that simple.

**Comment by simone-silvestri** [comment]
should be closed
