### ISSUE TITLE
Infrastructure for regridding and restarting Neverworld2 output at higher resolution

### ISSUE THREAD

**Issue by glwagner** [CliMA/ClimaOcean.jl#21]
In order to run a hierarchy of Neverworld2 simulations, we need to be able to regrid the state from a Neverworld2 simulation to a higher resolution.

For this we can use `regrid!`, and possibly also `diffuse_tracers!` to smooth fields out. We may also need `continue_downwards!` (hopefully we don't need horizontal inpainting?)

cc @simone-silvestri @sandreza @navidcy

**Comment by navidcy** [comment]
I think this is stale; NeverWorld2 moved out of the repo?

**Comment by glwagner** [comment]
true
