### ISSUE TITLE
Docstring style

### ISSUE THREAD

**Issue by glwagner** [CliMA/ClimaOcean.jl#227]
In Oceananigans most of our docstrings use a style where positional and keyword arguments are described in a sentence or two. Then, after the last sentence, we may be write "Default: x."

In ClimaOcean, I have found many docstrings that use a different style where the parenthetical "(default: x)" is used. For example

https://github.com/CliMA/ClimaOcean.jl/blob/9c858b0152fb5cff53b845878b7c9d68c762f54b/src/OceanSeaIceModels/CrossRealmFluxes/radiation.jl#L27-L40

Also, it seems that many docstrings write "# Arguments" instead of simply "Arguments". I believe most Oceananigans docstrings just use "Arguments". 

We should use a consistent style. I could see us changing Oceananigans. But this should be an intentional choice rather than just coming together randomly.

Where does the "#" come from and why is it desired? Do we want to use "Default: X" or "(default: x)"? Personally I prefer the Oceananigans style because it has less characters, I don't like the ().

A third option is to follow what's illustrated in the julia documentation which would be

```julia
Arguments 
 ========
  
 - `arch=CPU()`: The architecture of the system.
 - `FT=Float64`: The floating-point type to use.
  
Keyword Arguments 
 ===============
  
 - `ocean_emissivity=0.97`: The emissivity of the ocean surface.
 ```

**Comment by navidcy** [comment]
```
# Arguments
===========
```
is even wrong; it renders weirdly.

Should be either

```
# Arguments
```

or

```
Arguments
=========
```

Let's go with the latter!

**Comment by glwagner** [comment]
on style for defaults: a "written" style for defaults suits us I think because our defaults can be complicated (ie depend on other arguments). That's an argument for "Default: X" as opposed the more concise style recommended by julia docs

**Comment by simone-silvestri** [comment]
Agreed, `Default: X` is better than in parenthesis.
