### ISSUE TITLE
`ECCORestoring` method accepts architecture and grid; validation required?

### ISSUE THREAD

**Issue by navidcy** [CliMA/ClimaOcean.jl#231]
Do we want to check whether `architecture` is different from that of grid's? Does it matter?

https://github.com/CliMA/ClimaOcean.jl/blob/2e3ce57f23922dd557abe56b111eb380b39f987d/src/DataWrangling/ECCO/ECCO_restoring.jl#L309-L316

**Comment by glwagner** [comment]
It does matter.

Note that `grid` does more than might appear based on the interface --- `grid` signifies that the ECCO data should be _pre-interpolated_ to `grid` when it is loaded from file.

Also I think there is a bug and it doesn't work. We need to test this. Haha.

And of course in addition to writing jst the basic tests, some nice validation and error checking for users would be nice too.

**Comment by sb4233** [comment]
Was trying to run the Mediterranean regional setup - https://github.com/CliMA/ClimaOcean.jl/blob/05e6de31ba58594775f739cca47e6ae0ffbf3385/examples/mediterranean_simulation_with_ecco_restoring.jl#L1-L208

Got the following errors - 
 
 first it gives
 ```julia
unsupported keyword argument "connected_regions_allowed"
```
for  -
https://github.com/CliMA/ClimaOcean.jl/blob/05e6de31ba58594775f739cca47e6ae0ffbf3385/examples/mediterranean_simulation_with_ecco_restoring.jl#L66

**(Full error)**
 ```julia
ERROR: LoadError: MethodError: no method matching regrid_bathymetry(::LatitudeLongitudeGrid{Float64, Bounded, Bounded, Bounded, OffsetArrays.OffsetVector{Float64, CUDA.CuArray{Float64, 1, CUDA.DeviceMemory}}, Float64, Float64, Float64, OffsetArrays.OffsetVector{Float64, CUDA.CuArray{Float64, 1, CUDA.DeviceMemory}}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, OffsetArrays.OffsetVector{Float64, CUDA.CuArray{Float64, 1, CUDA.DeviceMemory}}, GPU}; height_above_water::Int64, minimum_depth::Int64, interpolation_passes::Int64, connected_regions_allowed::Int64)
This error has been manually thrown, explicitly, so the method may exist but be intentionally marked as unimplemented.

Closest candidates are:
  regrid_bathymetry(::Any; height_above_water, minimum_depth, dir, url, filename, interpolation_passes, major_basins) got unsupported keyword argument "connected_regions_allowed"
   @ ClimaOcean /g/data/er50/sb4233/.julia/packages/ClimaOcean/nctgo/src/Bathymetry.jl:85

Stacktrace:
 [1] kwerr(::@NamedTuple{height_above_water::Int64, minimum_depth::Int64, interpolation_passes::Int64, connected_regions_allowed::Int64}, ::Function, ::LatitudeLongitudeGrid{Float64, Bounded, Bounded, Bounded, OffsetArrays.OffsetVector{Float64, CUDA.CuArray{Float64, 1, CUDA.DeviceMemory}}, Float64, Float64, Float64, OffsetArrays.OffsetVector{Float64, CUDA.CuArray{Float64, 1, CUDA.DeviceMemory}}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, OffsetArrays.OffsetVector{Float64, CUDA.CuArray{Float64, 1, CUDA.DeviceMemory}}, GPU})
   @ Base ./error.jl:165
 [2] top-level scope
   @ /g/data/er50/sb4233/Oceananigans/test_julia/ClimaOcean.jl/examples/mediterranean_simulation_with_ecco_restoring.jl:62
in expression starting at /g/data/er50/sb4233/Oceananigans/test_julia/ClimaOcean.jl/examples/mediterranean_simulation_with_ecco_restoring.jl:62
```

Then if I try to remove the `connected_regions_allowed` argument and proceed, I get -

```julia
ERROR: LoadError: UndefVarError: `ECCO_restoring_forcing` not defined in `Main`
Suggestion: check for spelling errors or missing imports.
Stacktrace:
 [1] top-level scope
   @ /g/data/er50/sb4233/Oceananigans/test_julia/ClimaOcean.jl/examples/mediterranean_simulation_with_ecco_restoring.jl:81
in expression starting at /g/data/er50/sb4233/Oceananigans/test_julia/ClimaOcean.jl/examples/mediterranean_simulation_with_ecco_restoring.jl:81
```

**Comment by glwagner** [comment]
> Was trying to run the Mediterranean regional setup -
> 
> https://github.com/CliMA/ClimaOcean.jl/blob/05e6de31ba58594775f739cca47e6ae0ffbf3385/examples/mediterranean_simulation_with_ecco_restoring.jl#L1-L208
> 
> Got the following errors -
> 
> first it gives
> 
> ```julia
> unsupported keyword argument "connected_regions_allowed"
> ```
> 
> for -
> 
> https://github.com/CliMA/ClimaOcean.jl/blob/05e6de31ba58594775f739cca47e6ae0ffbf3385/examples/mediterranean_simulation_with_ecco_restoring.jl#L66
> 
> **(Full error)**
> 
> ```julia
> ERROR: LoadError: MethodError: no method matching regrid_bathymetry(::LatitudeLongitudeGrid{Float64, Bounded, Bounded, Bounded, OffsetArrays.OffsetVector{Float64, CUDA.CuArray{Float64, 1, CUDA.DeviceMemory}}, Float64, Float64, Float64, OffsetArrays.OffsetVector{Float64, CUDA.CuArray{Float64, 1, CUDA.DeviceMemory}}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, OffsetArrays.OffsetVector{Float64, CUDA.CuArray{Float64, 1, CUDA.DeviceMemory}}, GPU}; height_above_water::Int64, minimum_depth::Int64, interpolation_passes::Int64, connected_regions_allowed::Int64)
> This error has been manually thrown, explicitly, so the method may exist but be intentionally marked as unimplemented.
> 
> Closest candidates are:
>  regrid_bathymetry(::Any; height_above_water, minimum_depth, dir, url, filename, interpolation_passes, major_basins) got unsupported keyword argument "connected_regions_allowed"
>   @ ClimaOcean /g/data/er50/sb4233/.julia/packages/ClimaOcean/nctgo/src/Bathymetry.jl:85
> 
> Stacktrace:
> [1] kwerr(::@NamedTuple{height_above_water::Int64, minimum_depth::Int64, interpolation_passes::Int64, connected_regions_allowed::Int64}, ::Function, ::LatitudeLongitudeGrid{Float64, Bounded, Bounded, Bounded, OffsetArrays.OffsetVector{Float64, CUDA.CuArray{Float64, 1, CUDA.DeviceMemory}}, Float64, Float64, Float64, OffsetArrays.OffsetVector{Float64, CUDA.CuArray{Float64, 1, CUDA.DeviceMemory}}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, OffsetArrays.OffsetVector{Float64, CUDA.CuArray{Float64, 1, CUDA.DeviceMemory}}, GPU})
>   @ Base ./error.jl:165
> [2] top-level scope
>   @ /g/data/er50/sb4233/Oceananigans/test_julia/ClimaOcean.jl/examples/mediterranean_simulation_with_ecco_restoring.jl:62
> in expression starting at /g/data/er50/sb4233/Oceananigans/test_julia/ClimaOcean.jl/examples/mediterranean_simulation_with_ecco_restoring.jl:62
> ```
> 
> Then if I try to remove the `connected_regions_allowed` argument and proceed, I get -
> 
> ```julia
> ERROR: LoadError: UndefVarError: `ECCO_restoring_forcing` not defined in `Main`
> Suggestion: check for spelling errors or missing imports.
> Stacktrace:
>  [1] top-level scope
>    @ /g/data/er50/sb4233/Oceananigans/test_julia/ClimaOcean.jl/examples/mediterranean_simulation_with_ecco_restoring.jl:81
> in expression starting at /g/data/er50/sb4233/Oceananigans/test_julia/ClimaOcean.jl/examples/mediterranean_simulation_with_ecco_restoring.jl:81
> ```

can you open a new issue for this? The syntax has changed. If you're able to update the script that is much appreciated. For cexample, you have to use `ECCOForcing` not `ECCO_restoring_forcing`.

**Comment by glwagner** [comment]
I think the grid / architecture should be positional arguments so that the user cannot possibly supply conflicting inputs

**Comment by simone-silvestri** [comment]
sounds good!
