### ISSUE TITLE
Why interpolate then `set!`, rather than just interpolate directly?

### ISSUE THREAD

**Issue by glwagner** [CliMA/ClimaOcean.jl#233]
`set!` for `ECCOMetadata` seems to have an extra step that allocates an extra field:

https://github.com/CliMA/ClimaOcean.jl/blob/ff9366b64e33dcb92e2cc942f497e524bf296437/src/DataWrangling/ECCO/ECCO.jl#L257-L259

Can we instead write

```julia
 interpolate!(field, f) 
```

and avoid the intermediate field?

**Comment by simone-silvestri** [comment]
right, only the interpolate should work fine
