### ISSUE TITLE
Not all `wget`s have `http-passwd`

### ISSUE THREAD

**Issue by Sbozzolo** [CliMA/ClimaOcean.jl#272]
My guess is that it was removed with `wget2`, released in 2021.

**Comment by glwagner** [comment]
@simone-silvestri is there a way we can use `Base.downloads`? @Sbozzolo thinks so.

**Comment by simone-silvestri** [comment]
We should write a `.netrc` file like they do in here:
https://github.com/evetion/SpaceLiDAR.jl/blob/688105ed50c71e9d8d02c52c7a83801da1728611/src/utils.jl#L122

**Comment by glwagner** [comment]
I think there is also a way to create a downloader than can do this right? I'm looking at the documentation:

https://github.com/JuliaLang/Downloads.jl

Here's what the ECCO website says to do:

![image](https://github.com/user-attachments/assets/fa20a68e-9bd8-42e4-80f4-0ef0ac1ac391)

We aren't doing what they recommend though:

https://github.com/CliMA/ClimaOcean.jl/blob/8057d1a18ac16ad3ee3e4fc416868062e4e0d2de/src/DataWrangling/ECCO/ECCO_metadata.jl#L237

Still probably better to avoid `cmd`.

**Comment by glwagner** [comment]
Why do we use `http-user` instead of `user`?

**Comment by Sbozzolo** [comment]
Yes, I think you should be able to create a custom downloader that posts the user and the password as part of the request (but I have never done anything like this).

**Comment by simone-silvestri** [comment]
I think we can close this
