### ISSUE TITLE
Incorret plot labels in "Near Global Ocean Simulation"

### ISSUE THREAD

**Issue by Sbozzolo** [CliMA/ClimaOcean.jl#289]
https://clima.github.io/ClimaOceanDocumentation/stable/literated/near_global_ocean_simulation/

The plots here show latitude going from 0 to 600 and longitude from 0 to more than 1250. 

![2024-12-08:11:11:34](https://github.com/user-attachments/assets/c7eccca7-4c2a-4fb5-94cf-1bbbd8e44774)

**Comment by navidcy** [comment]
True. The axes show i, j indices; not coords. 

Probably we need to enhance Oceananigas Makie Ext

**Comment by glwagner** [comment]
I think an easier fix would be to supply the coordinates explicitly
