### ISSUE TITLE
ClimaOcean uses renamed Oceananigans.BuoyancyModel

### ISSUE THREAD

**Issue by jlk9** [CliMA/ClimaOcean.jl#299]
Oceananigans 95.0 renamed `BuoyancyModel` to `BuoyancyFormulation` and `Buoyancy` to `BuoyancyForce`. References to these modules need to be updated in ClimaOcean, such as https://github.com/CliMA/ClimaOcean.jl/blob/c00a4b6619e08f09379b2b3bff826df791f1293d/src/OceanSeaIceModels/ocean_sea_ice_model.jl#L4

**Comment by glwagner** [comment]
This is being resolved by https://github.com/CliMA/ClimaOcean.jl/pull/297
