### ISSUE TITLE
`regrid_bathymetry` docs

### ISSUE THREAD

**Issue by navidcy** [CliMA/ClimaOcean.jl#51]
The docstring seems to be missing info.

https://github.com/CliMA/ClimaOcean.jl/blob/99268b90678005cc7557b060b5ad03a065c9f856/src/Bathymetry.jl#L14-L30

Also, the function seems to be returning always a 1-degree bathymetry or is this bad variable naming?

https://github.com/CliMA/ClimaOcean.jl/blob/99268b90678005cc7557b060b5ad03a065c9f856/src/Bathymetry.jl#L155

cc @glwagner

**Comment by glwagner** [comment]
ah, just bad variable naming
