### ISSUE TITLE
Nuke `neverworld_simulation.jl`

### ISSUE THREAD

**Issue by glwagner** [CliMA/ClimaOcean.jl#53]
@sandreza @simone-silvestri 

Unfortunately nobody started using `neverworld_simulation` in `ClimaOcean.jl`. Since it takes work to maintain, I'm going to nuke it. Raising this issue in case you have changed your mind and would like to conduct your neverworld work here after all.

Here's the code: https://github.com/CliMA/ClimaOcean.jl/blob/main/src/IdealizedSimulations/neverworld_simulation.jl

**Comment by simone-silvestri** [comment]
I am not sure, it sounds bad to nuke the whole code. I think it might become of interest to people in the future. But if it's a burden to maintain especially now that ClimaOcean is "starting" and will probably go through many refactors, it is probably best to nuke it.

**Comment by glwagner** [comment]
Yes, if there were no other trade-off we wouldn't need to delete it. It will be in git history for anyone who would like to update the old code to use it.
