### ISSUE TITLE
Error in `runtests_setup.jl`

### ISSUE THREAD

**Issue by francispoulin** [CliMA/ClimaOcean.jl#94]
I tried running all the tests and most of them did not run for me.   I will copy the errors below, but I presume I need to do something else before I can run the tests or use this library?

```ERROR: LoadError: UndefVarError: `OceanSeaIceModels` not defined```

```JRA55 and data wrangling utilities: Error During Test at /home/fpoulin/Software/ClimaOcean.jl/test/test_jra55.jl:3
  Got exception outside of a @test
  UndefVarError: `JRA55_field_time_series` not defined
```

```
ECCO2 fields utilities: Error During Test at /home/fpoulin/Software/ClimaOcean.jl/test/test_ecco2.jl:7
  Got exception outside of a @test
  KeyError: key :sea_ice_thickness not found
```

```
Availability of JRA55 data: Error During Test at /home/fpoulin/Software/ClimaOcean.jl/test/test_downloading.jl:3
  Got exception outside of a @test
  UndefVarError: `JRA55_variable_names` not defined
```

**Comment by glwagner** [comment]
Can we use just one issue per problem?

How did you run the tests / how can we reproduce the errors that you are finding?

**Comment by francispoulin** [comment]
Sorry for not replying to this sooner. 

I'll address each issue one at a time, and change the title.

**Comment by francispoulin** [comment]
I have updated the repository and tried running `runtests_setup.jl`.  When I do I get a problem wtih `ECCO` not defined.  Please see below.

```
ulia> include("runtests_setup.jl")
ERROR: LoadError: UndefVarError: `ECCO` not defined
Stacktrace:
 [1] include(fname::String)
   @ Base.MainInclude ./client.jl:489
 [2] top-level scope
   @ REPL[1]:1
in expression starting at /home/fpoulin/Software/ClimaOcean.jl/test/runtests_setup.jl:7
```

**Comment by glwagner** [comment]
Make sure you are using the latest version of `ClimaOcean`

**Comment by francispoulin** [comment]
Thanks!

I did have the latest version of ClimaOcean installed, v0.1.3, but I was running julia.  When I start `julia --project`, I'm happy to say that it runs.

I'll close this and see whether the other tests pass.  If any fail I'll start an another issue but I suspect they will work fine now. Sorry for my careless mistake.

**Comment by glwagner** [comment]
It's ok! I suggest removing ClimaOcean and Oceananigans from your global environment (in fact I suggest removing anything you aren't actively using, I only keep plotting stuff in there)
